# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # GithubRepoBundle\:
    #     resource: '../../../GithubRepoBundle/*'
    #     exclude: '../../../GithubRepoBundle/{Entity,Repository,Tests}'
    #     arguments: [
    #         "@eight_points_guzzle.client.api_public_github", 
    #         "doctrine.orm.default_entity_manager",
    #         "githubrepo.manager",
    #         "githubrepo.public.api"
    #         ]

    GithubRepoBundle\Controller\:
        resource: '../../../GithubRepoBundle/Controller'
        public: true

    GithubRepoBundle\Command\:
        resource: '../../../GithubRepoBundle/Command'
        public: true
        tags:
            - { name: monolog.logger, channel: "githubRepo_command_channel" }

    githubrepo.manager:
        class: GithubRepoBundle\Services\GithubRepoManager

    githubrepo.public.api:
        class: GithubRepoBundle\Services\GithubRepoPublicApiClient
        arguments: [
            "@eight_points_guzzle.client.api_public_github",
            "@logger"
            ]
        tags:
            - { name: monolog.logger, channel: "githubRepo_publicApi_client_channel" }

    GithubRepoBundle\Services\GithubRepoPublicApiClient: "@githubrepo.public.api"
    GithubRepoBundle\Services\GithubRepoManager: "@githubrepo.manager"